# Generated by Django 4.2.16 on 2024-10-05 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='temp_loc',
            field=models.TextField(default='www.google.com'),
        ),
    ]
