# Generated by Django 4.2.16 on 2024-10-05 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_temp_loc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='temp_loc',
            field=models.TextField(),
        ),
    ]
