# Generated by Django 4.2.16 on 2024-10-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_post_slug_remove_post_temp_loc'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Sample_Template',
            field=models.TextField(default='https://www.google.com'),
        ),
    ]
