# Generated by Django 4.2.16 on 2024-10-07 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_sample_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Sample_Template',
            field=models.TextField(max_length=500),
        ),
    ]
