# Generated by Django 4.2.16 on 2024-10-07 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_post_sample_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Sample_Template',
            field=models.TextField(verbose_name='Sample Usage'),
        ),
    ]
