# Generated by Django 4.2.16 on 2024-10-12 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_post_sample_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Sample_Template',
            field=models.TextField(blank=True, verbose_name='Sample Usage'),
        ),
        migrations.AlterModelTable(
            name='post',
            table='table1',
        ),
    ]
